
### Next Steps

1. Review findings and assign severity
2. Perform human review of evidence
3. Validate reproduction steps
4. Approve or reject findings
5. Export to customer report
6. Archive evidence package

---

*This report was automatically generated by the NHI Evidence Package Generator*
*Version: 1.0.0*
*Generated: {datetime.now(timezone.utc).isoformat()}*
""")
        
        return str(report_file)

def main():
    """Main entry point for evidence package generation"""
    
    print("╔" + "="*68 + "╗")
    print("║" + " "*15 + "📦 NHI EVIDENCE PACKAGE GENERATOR" + " "*14 + "║")
    print("║" + " "*8 + "OWASP-compliant evidence packaging for NHI findings" + " "*7 + "║")
    print("╚" + "="*68 + "╝")
    print()
    
    # Check for NHI report
    report_file = input("NHI Security Report JSON file: ").strip()
    
    if not os.path.exists(report_file):
        print(f"❌ File not found: {report_file}")
        return
    
    try:
        with open(report_file, 'r') as f:
            report = json.load(f)
        
        # Create generator
        generator = EvidencePackageGenerator()
        
        # Generate package
        print("\n🔍 Generating evidence package...")
        package = generator.generate_from_nhi_report(report)
        
        # Save package
        print("💾 Saving evidence package...")
        results = generator.save_evidence_package(package)
        
        print("\n✅ Evidence package generated successfully!")
        print(f"   📁 Package directory: {results['package_dir']}")
        print(f"   📄 Manifest file: {results['manifest_file']}")
        print(f"   📦 ZIP archive: {results['zip_file']}")
        print(f"   📋 Report file: {results['report_file']}")
        
        print("\n📋 Package Contents:")
        print(f"   • Manifest (YAML + JSON)")
        print(f"   • {len(package.artifacts)} evidence artifacts")
        print(f"   • {len(package.provenance)} provenance events")
        print(f"   • Chain of custody documentation")
        print(f"   • Human review template")
        print(f"   • Redaction log")
        print(f"   • Audit report")
        
        print("\n🔍 Verification:")
        print(f"   Manifest Hash: {package.manifest_hash[:16]}...")
        print("   To verify: Compare artifact hashes in manifest")
        print("   Chain of custody: Review audit log IDs")
        
    except Exception as e:
        print(f"❌ Error generating evidence package: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    main()
